Port project over to GPLv3
MosesofEgypt/reclaimer pull request #21
Opened 2020-01-05 16:52 UTC by gbMichelle

Apply GPLv3 license notices to all files with code in them.

Btw, remember how I work with an editor that trims trailing whitespace? Yeah...

2020-01-05 20:09 UTC, MosesofEgypt commented on os_v4_hek/defs/weap.py
> -from ...os_v3_hek.defs.weap import *
This import should not be removed.

2020-01-05 20:25 UTC, MosesofEgypt requested changes
os_v4_hek.defs.weap is missing an import

2020-01-05 21:34 UTC, MosesofEgypt requested changes

2020-01-05 21:34 UTC, MosesofEgypt commented on os_v4_hek/defs/weap.py
> +from .weap import *
This is a recursive self import. It needs to be

```python
from ...os_v3_hek.defs.weap import *
```

2020-01-06 07:32 UTC, Mimickal commented on os_hek/handler.py
> -import os
Is this an unused import?

2020-01-06 07:32 UTC, Mimickal commented on shadowrun_prototype/handler.py
> -import os
Unused import?

2020-01-06 07:32 UTC, Mimickal commented on stubbs/handler.py
> -import os
Same thing?

2020-01-06 17:55 UTC, MosesofEgypt commented on os_hek/handler.py
> -import os
yes

2020-01-06 17:56 UTC, MosesofEgypt commented on shadowrun_prototype/handler.py
> -import os
double yes

2020-01-06 17:57 UTC, MosesofEgypt commented on stubbs/handler.py
> -import os
tr-tr-tr-triple yes

2020-01-06 18:00 UTC, MosesofEgypt approved these changes
Changes look good

2020-01-07 04:48 UTC, merged